name: front-deploy

on:
  pull_request:
    branches: main
    types: [closed]
    paths:
      - 'apps/form-fe/**'

jobs:
  front-deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    steps:
      - name: main branch
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_SSH_HOST }}
          username: ${{ secrets.REMOTE_SSH_UESRNAME }}
          password: ${{ secrets.REMOTE_SSH_PASSWORD }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script_stop: true
          script: |
            cd /server/googleform-client
            git pull
            pnpm install
            cd /server/googleform-client/apps/form-fe
            pnpm build
            pm2 reload googleform-front-5601
